# Generated by Django 5.0.8 on 2026-06-27 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_sprint2_forward_core'),
        ('monitoring', '0002_monitoring_engine_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Backup Job')),
                ('provider', models.CharField(blank=True, max_length=80, verbose_name='Provider')),
                ('schedule', models.CharField(blank=True, max_length=120, verbose_name='Schedule')),
                ('last_status', models.CharField(default='unknown', max_length=30, verbose_name='Last Status')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='core.company', verbose_name='Customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('protected_assets', models.ManyToManyField(blank=True, related_name='backup_jobs', to='monitoring.device', verbose_name='Protected Assets')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Job',
                'verbose_name_plural': 'Backup Jobs',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Service Name')),
                ('owner', models.CharField(blank=True, max_length=120, verbose_name='Owner')),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Criticality')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_services', to='core.company', verbose_name='Customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(blank=True, related_name='business_services', to='monitoring.device', verbose_name='Related Assets')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Service',
                'verbose_name_plural': 'Business Services',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Application Name')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Criticality')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.company', verbose_name='Customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('primary_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_applications', to='monitoring.device', verbose_name='Primary Asset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cmdb.businessservice', verbose_name='Business Service')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required')),
                ('impact_weight', models.PositiveSmallIntegerField(default=50, verbose_name='Impact Weight')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dependencies', to='monitoring.device', verbose_name='Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='cmdb.businessservice', verbose_name='Business Service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Dependency',
                'verbose_name_plural': 'Service Dependencies',
                'ordering': ['service__company__name', 'service__name', 'asset__name'],
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('depends_on', 'Depends on'), ('hosts', 'Hosts'), ('runs_on', 'Runs on'), ('connected_to', 'Connected to'), ('backed_up_by', 'Backed up by'), ('protects', 'Protects'), ('powers', 'Powers'), ('monitors', 'Monitors'), ('related', 'Related')], default='related', max_length=30, verbose_name='Relationship Type')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Label')),
                ('impact_weight', models.PositiveSmallIntegerField(default=50, help_text='0-100 impact score used by root cause analysis.', verbose_name='Impact Weight')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='monitoring.device', verbose_name='Source Asset')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='monitoring.device', verbose_name='Target Asset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Relationship',
                'verbose_name_plural': 'Asset Relationships',
                'ordering': ['source__company__name', 'source__name', 'relationship_type'],
                'indexes': [models.Index(fields=['relationship_type'], name='cmdb_assetr_relatio_9b0aa2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetrelationship',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relationship_type'), name='uniq_cmdb_asset_relationship'),
        ),
        migrations.AddIndex(
            model_name='businessservice',
            index=models.Index(fields=['company', 'criticality'], name='cmdb_busine_company_3679ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.UniqueConstraint(fields=('service', 'asset'), name='uniq_cmdb_service_asset_dependency'),
        ),
    ]
