# Generated by Django 5.0.6 on 2026-06-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitoring_engine_foundation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkresult',
            new_name='monitoring__device__50329e_idx',
            old_name='monitoring__device__e385b9_idx',
        ),
        migrations.RenameIndex(
            model_name='checkresult',
            new_name='monitoring__monitor_7b391f_idx',
            old_name='monitoring__check_i_35aa88_idx',
        ),
        migrations.RenameIndex(
            model_name='checkresult',
            new_name='monitoring__success_55316a_idx',
            old_name='monitoring__success_8a2988_idx',
        ),
    ]
