# Generated by Bilmad NOC Sprint 3.2
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=64, verbose_name='IP Aralığı')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20, verbose_name='Durum')),
                ('scan_ping', models.BooleanField(default=True, verbose_name='Ping')),
                ('scan_tcp', models.BooleanField(default=True, verbose_name='TCP')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='core.company', verbose_name='Firma')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_runs', to='core.location', verbose_name='Lokasyon')),
            ],
            options={
                'verbose_name': 'Keşif Taraması',
                'verbose_name_plural': 'Keşif Taramaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('hostname', models.CharField(blank=True, max_length=150, verbose_name='Hostname')),
                ('suggested_name', models.CharField(blank=True, max_length=180, verbose_name='Önerilen Ad')),
                ('suggested_type', models.CharField(choices=[('server', 'Sunucu'), ('vmware', 'VMware ESXi'), ('switch', 'Switch'), ('access_point', 'Access Point'), ('firewall', 'Firewall'), ('router', 'Router'), ('backup', 'Backup Sistemi'), ('sensway', 'Ortam Sensörü'), ('cctv_nvr', 'NVR/DVR'), ('cctv_camera', 'Kamera'), ('alarm_panel', 'Alarm Paneli'), ('m365', 'Microsoft 365'), ('security', 'Güvenlik Sistemi'), ('other', 'Diğer')], default='other', max_length=40, verbose_name='Önerilen Tip')),
                ('open_ports', models.JSONField(blank=True, default=list, verbose_name='Açık Portlar')),
                ('confidence', models.PositiveIntegerField(default=50, verbose_name='Güven')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='discovery.discoveryrun')),
                ('imported_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_sources', to='monitoring.device')),
            ],
            options={
                'verbose_name': 'Keşfedilen Host',
                'verbose_name_plural': 'Keşfedilen Hostlar',
                'ordering': ['ip_address'],
                'unique_together': {('discovery_run', 'ip_address')},
            },
        ),
    ]
